
FROM golang:1.24 AS builder

WORKDIR /usr/src/app

# Copia os arquivos necessários
COPY go.mod .  
RUN go mod tidy  

COPY . .

# Compila o binário de forma estática
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app main.go

# ---- Fase 2: Imagem final ultra leve ----
FROM scratch

# Copia apenas o binário compilado
COPY --from=builder /app /app

# Define o binário como comando principal
CMD ["/app"]
    